#!/bin/sh
#author mengll
#version 0.1
#desc 安装python3.6版本

#安装路径
yum install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gcc make
if [ $? -ne 0 ];then
  exit 1
fi

installDir=/usr/local/python3
pName=Python-3.6.2.tgz
cd /usr/local/src
#获取
if [ ! -e $pName ];then
   wget -c https://www.python.org/ftp/python/3.6.2/Python-3.6.2.tgz
fi

if [ $? -eq 0 ];then
        tar -zxvf $pName
        if [ $? -eq 0 ];then
            #解压
            cd Python-3.6.2
            ./configure --prefix=/usr/local/python3
            make && make install
           #安装当
           if [ $? -eq 0 ];then
                $installDir/bin/pip3.6 install pymysql xlrd
                if [ $? -eq 0 ];then
                        echo -e "\E[32m 安装成功 \E[0m"
                fi
            else
                echo -e "\E[31m 安装失败 \E[0m"
           fi
        fi
fi

echo "start config!"

ln -s /usr/local/python3/bin/python3.6 /usr/bin/python3

if [ $? -ne 0 ];then
   echo "python link create error!"
 else
    echo -e "\E[32m 安装成功 \E[0m"
fi

ln -s /usr/local/python3/bin/pip3 /usr/bin/pip3

if [ $? -ne 0 ];then
   echo "\E[31m安装失败\E[0m"
 else
   echo -e "\E[32m 安装成功 \E[0m"
fi



